# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f1a2294ad8f3d0ba50e6c81644b698aaf289df16ab2548978c0af0f1c3e889f23b13d4f63388cccc12dc8dffd5f459e11ea8e440249712844d93a95fd82417

test:
  secret_key_base: 39796e0011cbeaa7cbcef7a69c5b65a14b1260b24bd21c6d8646d2b2f111996e0d13f9368b15196bbff96f88c74c695b0ab5350c1d4a968f3c6778ed0c0601a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
